# Generated by Django 4.0.4 on 2022-05-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=30)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=280)),
                ('image', models.ImageField(blank=True, upload_to='static/images')),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
