# Generated by Django 4.0.4 on 2022-05-23 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_picture_remove_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linguagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('ano', models.IntegerField()),
                ('descricao', models.TextField()),
                ('docente_teorica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.professor')),
                ('docentes_praticas', models.ManyToManyField(related_name='caderias', to='portfolio.professor')),
                ('linguagens', models.ManyToManyField(to='portfolio.linguagem')),
                ('projetos', models.ManyToManyField(to='portfolio.projeto')),
            ],
        ),
    ]
