# Generated by Django 4.0.4 on 2022-05-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_linguagem_professor_projeto_cadeira'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='imagce',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='docentes_praticas',
            field=models.ManyToManyField(related_name='cadeiras', to='portfolio.professor'),
        ),
    ]
