# Generated by Django 4.0.4 on 2022-05-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_rename_imagce_projeto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='descricao',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='nome',
            field=models.CharField(default='', max_length=20),
        ),
    ]
