# Generated by Django 4.0.4 on 2022-05-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_projeto_descricao_alter_cadeira_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(max_length=300),
        ),
    ]
