# Generated by Django 4.0.4 on 2022-05-27 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_cadeira_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor_P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('linkedin', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cadeira',
            name='docentes_praticas',
        ),
        migrations.RemoveField(
            model_name='cadeira',
            name='projetos',
        ),
        migrations.AddField(
            model_name='cadeira',
            name='projetos',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='portfolio.projeto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadeira',
            name='docentes_praticas',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='portfolio.professor_p'),
            preserve_default=False,
        ),
    ]
