# Generated by Django 4.0.4 on 2022-06-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_post_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=50)),
                ('curso', models.CharField(default='', max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.CreateModel(
            name='Tfc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('titulo', models.CharField(default='', max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('link', models.URLField(blank=True)),
                ('linkgithub', models.URLField(blank=True)),
                ('video', models.FileField(null=True, upload_to='')),
                ('autores', models.ManyToManyField(to='portfolio.autor')),
                ('orientadores', models.ManyToManyField(to='portfolio.professor')),
            ],
        ),
    ]
